# Generated by Django 6.0.7 on 2026-09-27 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='display_name',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
