# Generated by Django 6.0.7 on 2026-09-27 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_account_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='avatar',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
        migrations.AddField(
            model_name='account',
            name='bio',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='account',
            name='coolapk',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='account',
            name='qq',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='account',
            name='show_in_team',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='team_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='account',
            name='title',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
