# Generated by Django 6.0.7 on 2026-09-27 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_account_avatar_account_bio_account_coolapk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='helper_flag',
            field=models.IntegerField(default=0),
        ),
    ]
